import type { Metadata } from "next";
// Remove the remote font import from next/font/google
// import { Geist, Geist_Mono } from "next/font/google";
// Use local fonts via Fontsource:
import "@fontsource/inter/400.css"; // Regular weight
import "@fontsource/inter/700.css"; // Bold weight
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
